# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=50)),
                ('Game1', models.DateTimeField(verbose_name='date published')),
                ('Game2', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
