# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='Game1_Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='Game2_Score',
            field=models.IntegerField(default=0),
        ),
    ]
